### ISSUE TITLE
Cannot compile with Typescript 3.5.3+

### ISSUE THREAD

**Issue by ChristopherKiss** [Colonise/Utilities#7]
```
ERROR in ../node_modules/@colonise/utilities/objects/extract.d.ts:8:779 - error TS2589: Type instantiation is excessively deep and possibly infinite.

8 export declare function extract<TObject, TProperty1 extends keyof Defined<TObject>, TProperty2 extends keyof Defined<Defined<TObject>[TProperty1]>, TProperty3 extends keyof Defined<Defined<Defined<TObject>[TProperty1]>[TProperty2]>, TProperty4 extends keyof 
Defined<Defined<Defined<Defined<TObject>[TProperty1]>[TProperty2]>[TProperty3]>, TProperty5 extends keyof Defined<Defined<Defined<Defined<Defined<TObject>[TProperty1]>[TProperty2]>[TProperty3]>[TProperty4]>, TProperty6 extends keyof Defined<Defined<Defined<Defined<Defined<Defined<TObject>[TProperty1]>[TProperty2]>[TProperty3]>[TProperty4]>[TProperty5]>>(object: TObject, property1: TProperty1, property2: TProperty2, property3: TProperty3, property4: TProperty4, property5: TProperty5, property6: TProperty6): Defined<Defined<Defined<Defined<Defined<Defined<Defined<TObject>[TProperty1]>[TProperty2]>[TProperty3]>[TProperty4]>[TProperty5]>[TProperty6]> | undefined;
```

**Comment by pathurs** [comment]
@ChristopherKiss now that TypeScript has Optional Chaining, I think `extract()` is not needed anymore.

**Comment by ChristopherKiss** [comment]
Yes, will be moving over to that once we can jump to Angular 9, and have had to remove utilities package as even removing all imports of extract, still fails to compile, so needed to remove all imports to the entire package. :(

**Comment by pathurs** [comment]
if https://github.com/Colonise/Utilities/commit/fccdf2c483ab34ba410c57851c270d77213230fa publishes then we can close this
